// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RabbitContainer
{
    internal sealed partial class Vsix
    {
        public const string Id = "RabbitContainer.0826c438-f591-4e88-ac5d-f7426da72335";
        public const string Name = "RabbitContainer";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "pchuan98";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
