// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RabbitContainer
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string RabbitContainerString = "e85d182a-f11b-4b4f-8fdc-cdfafe7b0d25";
        public static Guid RabbitContainer = new Guid(RabbitContainerString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        // Slot groups for external extension placement
        public const int EditorContextMenuGroup = 0x0001;
        public const int FileItemContextMenuGroup = 0x0002;
        public const int FolderContextMenuGroup = 0x0003;
        public const int ProjectContextMenuGroup = 0x0004;
        public const int SolutionContextMenuGroup = 0x0005;

        // Test commands
        public const int TestEditorCommand = 0x0100;
        public const int TestFileItemCommand = 0x0101;
        public const int TestFolderCommand = 0x0102;
        public const int TestProjectCommand = 0x0103;
        public const int TestSolutionCommand = 0x0104;
    }
}
